#+TITLE melpazoid
#+OPTINS: toc:3 author:t creator:nil num:nil
#+AUTHOR Chris Rayner
#+EMAIL: dchrisrayner@gmail.com

[[https://travis-ci.org/riscy/shx-for-emacs][https://travis-ci.org/riscy/melpazoid.svg?branch=master]]

* Description
  /melpazoid/ is a bundle of scripts for testing Emacs packages, primarily
  submissions to [[https://github.com/melpa/][MELPA]]. The ambition is to have checks that run in an "clean"
  environment, either through CI or through a container on your local machine.

* Use Travis
  Fork this repository and open a PR against it that modifies the ~.travis.yml~
  file with your recipe and your clone address.  The build information on your
  pull request will report any discovered issues.

* Local install
  You will need Python >= 3.6 (along with the ~requests~ package) and Docker.

** Test your MELPA PR
   1. Run `make`
   2. Copy and paste the URL of your MELPA PR into the console

   A Docker container will be built with (hopefully) all of your requirements
   installed.  The output scroll will report any discovered issues.
** Test a local package
   TODO
** Test a remote package
   TODO
