name: test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with: { python-version: '3.10' }
    - name: Install
      run: |
        sudo apt-get install emacs
        emacs --version
        pip install . mypy pytest ruff
    - name: Test
      run: make test-melpazoid

    - name: Test 'shx' Pull Request  # a small package with few dependencies
      env:  
        CI_BRANCH: main    # always build the main branch for this repo
        EXIST_OK: true     # we expect that it already exists on MELPA
      run: MELPA_PR_URL=https://github.com/melpa/melpa/pull/4749 make

    - name: Test 'kanban' Recipe  # notably this is a Mercurial recipe
      env:  
        CI_BRANCH: default # always build the default branch on this repo
        EXPECT_ERROR: 2    # we expect it to have some nags
      run: RECIPE='(kanban :fetcher hg :url "https://hg.sr.ht/~arnebab/kanban.el")' make

    - name: Test 'magit' Recipe  # magit is a large recipe
      env:
        CI_BRANCH: main    # always build the main branch on this repo
        EXPECT_ERROR: 2    # we expect it to have some nags
      run:
        RECIPE='(magit :fetcher github
                       :repo "magit/magit"
                       :files ("lisp/magit" "lisp/magit*.el" "lisp/git-rebase.el" "Documentation/magit.texi" "Documentation/AUTHORS.md" "LICENSE"
                              (:exclude "lisp/magit-libgit.el")))'
        make
    - name: Test local 'melpazoid'
      env:
        CI_BRANCH: main
        WARN_IS_ERROR: true
      run: python melpazoid/melpazoid.py . --license --recipe '(melpazoid :fetcher github :repo "riscy/melpazoid" :files ("melpazoid/melpazoid.el"))'
